spring:
  application:
    name: Restaurant

  datasource:
    url: jdbc:mysql://localhost:3306/restraunt
    username: root
    password: root123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
